version: '3.8'

services:
  db:
    image: postgres:16
    container_name: cataloghub-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=cataloghub
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    container_name: cataloghub-api
    build:
      context: .
      dockerfile: CatalogHub.Api/Dockerfile
    restart: always
    ports:
      - "8000:8080" 
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=db;Port=5432;Database=cataloghub;User Id=postgres;Password=password;

      - AWS__BucketName=SEU_BUCKETNAME
      - AWS__AWSAccessKey=SUA_ACCESSKEY
      - AWS__AWSSecretKey=SUA_SECRETKEY
      - AWS__Region=SUA_REGIAO_AWS
    depends_on:
      - db 

volumes:
  postgres_data: